name: 📕 Security issue
description: 📕 Report a documentation issue
title: "[📕Documentation issue] <title>"
labels: [Documentation]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: radio
  attributes:
    label: Type of issue
    description: What is the kind of issue with the documentation?
    options:
    - label: Mistake
    - label: Something is missing
    - label: Credit error
- type: textarea
  attributes:
    label: Documentation issue description
    description: What and where is the issue located on the documentation? 
  validations:
    required: false
- type: textarea
  attributes:
    label: Documentation info
    description: |
      examples:
        - **Version** : v.1.2.3
        - **Page/Location** : Introduction
    value: |
        - Version : v.
        - Page/Location : 
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
      - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [📕Code of Conduct](https://github.com/Stonks-Life-Inc/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true